feat(start_receiving): add parameter recv_time to allow delayed receiving
ProfFan/dw3000-ng pull request #6
Opened 2024-05-23 06:32 UTC by elrafoon

This allows i.e. saving power when it is known that response won't come sooner than some time T.

2024-05-23 20:15 UTC, ProfFan requested changes
API breaking in HL need to be fixed.

Thank you for the contribution!

2024-05-23 20:15 UTC, ProfFan commented on src/hl/ready.rs
> +    pub fn receive(
Please add a `receive` wrapper that have the same signature as before, and rename this to be `receive_delayed`

2024-05-23 20:15 UTC, ProfFan commented on src/hl/receiving.rs
> +                // By setting this register, the chip knows to delay before transmitting
```suggestion
                // By setting this register, the chip knows to delay before start receiving
```

2024-08-19 12:01 UTC, trembel commented
I think this can be closed after https://github.com/ProfFan/dw3000-ng/pull/11.

2024-08-19 14:19 UTC, closed without merging